sqs/urls.py
from django.conf.urls import url
from django.contrib import admin

import sqs.views as views


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$',views.index),
    url(r'^register$',views.register),
    url(r'^login$',views.login),
    url(r'^student$',views.student_view),
    url(r'^prepare_quiz$',views.prepare_quiz),
    url(r'^submit_quiz$',views.submit_quiz),
    url(r'^teacher$',views.teacher_view),
    url(r'^logout$',views.logout),
    url(r'^sqsadmin/$',views.admin),
    url(r'^sqsadmin/quiz_setup$',views.quiz_setup),
    url(r'^sqsadmin/add_school$',views.add_school),
    url(r'^sqsadmin/csv_upload$',views.csv_upload),

]

sqs/models.py
from django.db import models

class School(models.Model):
	sc_id = models.CharField(max_length=100,unique=True)
	school_name = models.CharField(max_length=100)
	city_name = models.CharField(max_length=100)

	def __str__(self):
		return self.school_name+'/'+self.city_name

class Student(models.Model):
	school = models.ForeignKey(School, related_name="students")
	login_id = models.CharField(max_length=100, unique=True)
	name = models.CharField(max_length=100)
	password = models.CharField(max_length=100)
	CHOICES = (('student','student'),('teacher','teacher'))
	user = models.CharField(max_length=100,choices=CHOICES,default="student")

	def __str__(self):
		return self.name+'/'+self.user


class Quiz(models.Model):
	title = models.CharField(max_length=200,unique=True)
	start_date = models.DateTimeField()
	end_date = models.DateTimeField()
	duration = models.IntegerField()

	def __str__(self):
		return self.title

class Question(models.Model):
	quiz = models.ForeignKey(Quiz, related_name = "questions")
	question_text = models.TextField()
	choice = models.IntegerField()

	def __str__(self):
		return self.question_text

class Answer(models.Model):
	question = models.ForeignKey(Question, related_name = "answers")
	answer_text = models.TextField()
	correct = models.BooleanField()

	def __str__(self):
		return self.answer_text

class StudentAnswers(models.Model):

	quiz_id = models.CharField(max_length=100)
	quiz_title = models.CharField(max_length=100,default='title')
	login_id = models.CharField(max_length=100)
	user_answers = models.CharField(max_length=1000)
	score = models.IntegerField(default=0)

	def __str__(self):
		return self.quiz_id+'/'+self.login_id

sqs/forms.py
from django import forms
from django.db import models

from .models import Student,School,Quiz,Question,Answer

class StudentForm(forms.ModelForm):
	class Meta:
		model = Student
		school = models.ForeignKey(School)
		password = forms.CharField(widget=forms.PasswordInput)
		widgets = {
            'password': forms.PasswordInput(),
        }
		fields = ('login_id','name','password','school','user')

class SchoolForm(forms.ModelForm):
	class Meta:
		model = School
		fields = ('sc_id','school_name','city_name')


class QuizForm(forms.ModelForm):
	class Meta:
		model = Quiz
		fields = ('title','start_date','end_date','duration')

	def process(self):
		start_date = self.cleaned_data.get("start_date")
		end_date = self.cleaned_data.get("end_date")
		duration = self.cleaned_data.get('duration')
		msg = ''
		if end_date <= start_date:
			msg = u"End date should be greater than start date."
			self._errors["end_date"] = self.error_class([msg])
		elif duration <= 0:
			msg = u"Invalid Duration"
			self._errors["duration"] = self.error_class([msg])
		return msg

class QuestionForm(forms.ModelForm):
	class Meta:
		model = Question
		exclude = ('quiz',)

class AnswerForm(forms.ModelForm):
	class Meta:
		model = Answer
		exclude = ('quiz',)

class UploadCSVForm(forms.Form):
	file = forms.FileField()

	def process_csv_file(csv):
		print (csv.name)

sqs/views.py
from django.contrib import messages
from django.shortcuts import render,render_to_response
from django.http import HttpResponse

from .forms import StudentForm,QuizForm,QuestionForm,AnswerForm,UploadCSVForm,SchoolForm
from .models import School,Student,Quiz,Question,Answer,StudentAnswers
from .serializers import QuizSerializer,SchoolSerializer

import csv,datetime,os
from json import loads,dumps


def index(request):
	context = {}
	if 'login_id' in request.session :
		context['login_id'] = request.session['login_id']
	if 'logged_user' in request.session:
		context['logged_user'] = request.session['logged_user']
	lbd = get_leaderboard()
	context['leaders'] = lbd['leaders']
	context['school_leaders'] = lbd['school_leaders']
	return render_to_response('index.html',context)

def register(request):
	if request.method == "POST":
		request.POST = request.POST.copy()
		request.POST['password'] = request.POST['password'].encode('base64').strip()
		form = StudentForm(request.POST)
		if form.is_valid():
			post = form.save(commit=False)
			post.save()
			messages.success(
				request,'Registration Success'
				)
	else:
		form = StudentForm(initial={'max_number': '3'})
	return render(request,'register.html',{'form':form})

def login(request):
	context = {}
	if request.method == "POST":
		password = request.POST['password'].encode('base64')
		student_list = Student.objects.filter(login_id=request.POST['loginid'],user=request.POST['user'])
		if len(student_list) < 1:
			messages.error(
				request,'No '+request.POST['user']+' Exists with login_id '+request.POST['loginid']
				)
		elif student_list[0].password != password.strip():
			messages.error(
				request,'Invalid Credentials'
				)
		else:
			request.session['login_id'] = request.POST['loginid']
			request.session['logged_user'] = request.POST['user']
			print( request.POST['user'])
	return render(request,'login.html',context)

def logout(request):
	if 'login_id' in request.session:
		request.session.pop('login_id')
		request.session.pop('logged_user')
	return render(request,'index.html',{})
def admin(request):
	return render(request,'admin.html',{})

def quiz_setup(request):
	if request.method == 'POST':
		form = QuizForm(request.POST)
		context = {'quizf':form}
		if form.is_valid():
			if form.process() == '':
				quiz_p = form.save()
				context['quiz_id'] = quiz_p.id
	else:
		form = QuizForm()
		context = {'quizf':form}
	return render(request,'quiz_setup.html',context)

def csv_upload(request):
	context = {'file_required':1}
	if request.method == 'POST':
		context['file_required'] = 0
		csv_file = request.FILES['csv_file']
		BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
		file_path = os.path.join(BASE_DIR,csv_file.name)
		try:
			location = open(file_path,'wb+')
		except Exception as e:
			print (e)
		for chunk in csv_file.chunks():
			location.write(chunk)
		location.close()
		try:
			process_csv(file_path,request.POST['quiz_id'])
			qser = QuizSerializer(Quiz.objects.get(pk=request.POST['quiz_id']))
			context['added_quiz'] = qser.data
		except Exception as e:
			print (e)
	return render(request,'csv_upload.html',context)


def process_csv(csv_file,quiz_id):
	csvfile = open(csv_file)
	contents = csvfile.readlines()
	pos = 0
	quizname = contents[pos]

	while(pos<len(contents)-1):
		pos += 1
		if contents[pos].strip() == '':
			break
		qtn = Question.objects.create(quiz_id=quiz_id,question_text=contents[pos],choice=contents[pos+1])
		pos += 1
		ans_c = int(contents[pos+int(contents[pos].strip())+1])
		for i in range(int(contents[pos])):
			if i+1 == ans_c:
				ans = Answer.objects.create(question=qtn,answer_text=contents[pos+1].strip(),correct=True)
			else:
				ans = Answer.objects.create(question=qtn,answer_text=contents[pos+1].strip(),correct=False)
			pos += 1
		pos += 1


def student_view(request):
	context = {}
	if 'login_id' in request.session:
		context = {'quizes':{}}
		student = Student.objects.get(login_id=request.session['login_id'])
		quizes = Quiz.objects.filter(end_date__gte=datetime.datetime.now())
		quizestaken = StudentAnswers.objects.filter(login_id=request.session['login_id'])
		quizestaken = {quizt.quiz_id:[str(quizt.quiz_title),str(quizt.score),quizt.user_answers] for quizt in quizestaken}
		context['quizestaken'] = quizestaken
		for i in quizes:
			if str(i.id) not in quizestaken:
				context['quizes'][i.id]=i.title
		context['schoolmates'] =[scm for scm in Student.objects.filter(school=student.school,user=student.user).exclude(id=student.id)]
		context['student_name'] = student.name

	return render(request,'student.html',context)
def teacher_view(request):
	context = {}
	if 'login_id' in request.session:
		student = Student.objects.get(login_id=request.session['login_id'])
		context['student_name'] = student.name
		school_students = get_school_dashboard(request.session['login_id'])
		if len(school_students)>0:
			context['school_students'] = school_students
		else:
			messages.error(request,'No Quizes data will be available right now')
	return render(request,'teacher.html',context)

def prepare_quiz(request):
	quiz_id = request.GET['quiz_id']
	quiz = Quiz.objects.get(pk=quiz_id)
	quiz_ser = QuizSerializer(quiz)
	quiz_ser = quiz_ser.data

	quiz_data = loads(dumps(quiz_ser))

	context = {'quiz_data':quiz_data}
	if(request.GET['display'] == 'quiz_details'):
		student_answers = eval(request.GET['student_answers'].replace("u'","'"))
		context['score'] = request.GET['score']
		print (student_answers)
		for question in quiz_data['questions']:
			if str(question['answers'][0]['question']) in student_answers:
				try:
					question['option'] = int(student_answers[str(question['answers'][0]['question'])])
				except Exception as e:
					question['option'] = student_answers[str(question['answers'][0]['question'])]
		#print quiz_data
	return render(request,request.GET['display']+'.html',context)

def submit_quiz(request):
	if request.method == 'POST':
		answers = loads(dumps(request.POST))
		answers.pop('csrfmiddlewaretoken')
		quiz_id = answers.pop('quiz_id')
		'''
		quiz = Quiz.objects.get(pk=quiz_id)
		quiz_ser = QuizSerializer(quiz)
		quiz_data = loads(dumps(quiz_ser.data))
		'''
		score = 0


		questions = [qtn.id for qtn in Question.objects.filter(quiz=quiz_id)]
		correct_ans_mult = Answer.objects.filter(question__in=questions,correct=True).exclude(question__choice=1)
		correct_ans_essay = Answer.objects.filter(question__in=questions,correct=True).exclude(question__choice__gt=1)
		
		for c_ans in correct_ans_mult:
			if (str(c_ans.question.id) in answers) and (str(c_ans.id) == answers[str(c_ans.question.id)]):
				score += 1
		for c_ans in correct_ans_essay:
			print( c_ans.answer_text,answers[str(c_ans.question.id)])
			if (c_ans.answer_text == answers[str(c_ans.question.id)]):
				score += 1
		
		StudentAnswers.objects.create(quiz_id=quiz_id,quiz_title=Quiz.objects.get(pk=quiz_id).title,login_id=request.session['login_id'],user_answers=answers,score=score)

		return HttpResponse("<p class='bg-success' style='padding:15px;font-weight:bold;'> Quiz Submitted </br>Result will be available in your Home <i class='glyphicon glyphicon-ok pull-right'></i></p>")

def get_leaderboard():
	quizes = Quiz.objects.all()
	leaders = []
	school_leaders = []
	for quiz in quizes:
		best = StudentAnswers.objects.filter(quiz_id=quiz.id).order_by('-score')
		st_ids = [st.login_id for st in best]
		students = Student.objects.filter(login_id__in=st_ids)
		for st_id in st_ids:
			student = students.get(login_id=st_id)
			leaders.append({'quiz_name':quiz.title,'school_name':student.school.school_name,'score':best.get(login_id=st_id).score,'student_name':student.name,'city_name':student.school.city_name})
			del st_id
		schools = School.objects.all()
		st_ids = [st.login_id for st in best]
		for school in schools:
			students = Student.objects.filter(login_id__in=st_ids).filter(school=school)
			sc_leaders=[]
			for student in students:
				sc_leaders.append({'quiz_name':quiz.title,'school_name':student.school.school_name,'score':best.get(login_id=student.login_id).score,'student_name':student.name})
				del st_ids[st_ids.index(student.login_id)]
			if len(sc_leaders) > 0:
				school_leaders.append(sc_leaders)
	return {'leaders':leaders,'school_leaders':school_leaders}

def get_school_dashboard(login_id):
	quizes = Quiz.objects.all()
	school = Student.objects.get(login_id=login_id).school
	students = SchoolSerializer(school)
	st_ids = {st['login_id']:st['name'] for st in students.data['students']}
	school_students = []
	
	for quiz in quizes:
		quizes_taken=[]
		attempted = StudentAnswers.objects.filter(login_id__in=st_ids.keys(),quiz_id=quiz.id).order_by('-score')
		for attempt in attempted:
			quizes_taken.append({'quiz_id':quiz.id,'student_name':st_ids[attempt.login_id],'login_id':attempt.login_id,'score':attempt.score,'student_answers':attempt.user_answers})
		if len(quizes_taken)>0:
			school_students.append({quiz.title:quizes_taken})
	
	return school_students

def add_school(request):
	if request.method == 'POST':
		form = SchoolForm(request.POST)
		if form.is_valid():
			form.save()
			messages.success(request,'New School Added')
	else:
		form = SchoolForm()
	return render(request,'add_school.html',{'school_form':form})

sqs/templates/add_school.html
{% if messages %}
	{% for message in messages %}
		<div class="alert alert-success">{{message}}</div>
	{% endfor %}
{% endif %}
<h4>Add New School</h4>
<form action="add_school" method="post" id="add_school_form">
	{% csrf_token %}
	<table class="table table-bordered">
		{{school_form.as_table}}
		<tr><td></td><td><button class="btn btn-info">Add</button></td></tr>
	</table>
</form>
<script type="text/javascript">
$('#add_school_form').submit(function( event ) {
  event.preventDefault();

  $.ajax({
  	url: "add_school",
  	method:'POST',
  	data:$(this).serialize(),
  	error:$('#add_school').html('Internal Error, Try Again'),
  	success:function(data){
  		$('#add_school').html(data);
  	},
  	complete:$('#add_school').html('loading...')
   });

});

</script>

sqs/templates/admin.html
{% load static %}
<html>
<script src = "{%static "jquery/jquery.js" %}"></script>
<script src = "{%static "jquery.form.js" %}"></script>
<script src = "{%static "js/bootstrap.min.js" %}"></script>
<link href="{%static "jquery-ui.css" %}" rel="stylesheet">
<link href="{%static "css/bootstrap.min.css" %}" rel="stylesheet">
<script src = "{%static "jquery-ui.js" %}"></script>
<style>
	body{
		font-family: "Trebuchet MS", sans-serif;
		margin: 50px 100px 100px 100px;
		min-width: 800px;
	}
	.options{
		text-align:right;
		cursor: pointer;
		display: inline-block;
	}
	.container{
		margin-top: 3%;
		padding-left:5%;
		border-bottom: 1px dotted grey;
		min-width: 800px;
	}

	.header h1{
		color:#2A2AD8;
	}
	a{
		color:#000;
	}
	</style>
<title>SQS Admin</title>
<div class="header">
<h1>Student's Quiz System</h1>
<div class="ui-widget" style="border-bottom: 1px dotted grey;">
	<div style="float:left;font-weight:bold">Quizes will be conducted here and you can check leaderboards</div>
	<div class="pull-right">
	<a class="btn options btn-info" href='/sqsadmin'>Home</a>
	<a class="btn options btn-success" target="blank" href='/'>Leaderboard</a>
	</div>
	<br></br>
</div>
</div>
<div class="container">
	<div class="row">
		<div id="add_school" class="col-md-6">
		</div>
		<div id="quiz_setup" class="col-md-6">
		</div>
	</div>
	<div class="row">
		<div style="width:60%;margin-left: auto;margin-right: auto;">
			<div class="alert alert-info">Instructions to CSV file formate. </div>
			1. After Adding Quiz You have to submit CSV file with question and answers in below formate.</br>
			2. First line will be Quiz Title.</br>
			3. Next line should be question text in single line.</br>
			4. No. of answers for above question (i.e choice/essay).For essay type answers it should be 1.</br>
			5. Next lines will be Each answer in single line.</br>
			6. Correct option for question. For essay type answers it should be 1.</br>
			7. Follow from 3rd instructions for next question. 

		</div>
	</div>
</div>

<script type="text/javascript">
	$.ajax({
	  	url: "quiz_setup",
	  	method:'GET',
	  	success:function(data){
	  		$('#quiz_setup').html(data);
	  	},
	  	complete:$('#quiz_setup').html('loading...')
	});

	$.ajax({
	  	url: "add_school",
	  	method:'GET',
	  	success:function(data){
	  		$('#add_school').html(data);
	  	},
	  	complete:$('#add_school').html('loading...')
	});

</script>

</html>

sqs/templates/csv_upload.html
<div id='csv_upload'>
<style>
blockquote{
		border-color:#AA6708;
		
	}
.answer{
		padding:15px;
		width: 70%;
		color:#43679C;
	}
</style>
{% if file_required %}
	<div class="alert alert-success">New Quiz Added, Please upload CSV file</div>
	<form method="post" action="csv_upload" enctype="multipart/form-data" id="process_csv">{% csrf_token %}
	<table class="table">
	<tr><td>CSV File</td><td><input type="file" name="csv_file" id="file" required></td></tr>
	<tr><td></td><td><input class="btn btn-info" type="submit" value="Process CSV"></td></tr>
	<tr><td colspan="2"><strong>*CSV File Should be formatted mentioned below</strong></td></tr>
	</table>
	</form>
	</div>

	{% else %}
		<div>
			<div class="alert alert-success">Below added quiz will be reflected to students on mentioned dates</div>
			<h4>{{added_quiz.title}} <span class="pull-right">Duration:{{added_quiz.duration}} mins</span></h4> 
		</div>
		<div>
			{% for question in added_quiz.questions %}
				<blockquote>
					<p><strong>{{question.question_text}} </strong></p>
					{% if question.choice == 1 %}
						<p class="answer bg-success">{{question.answers.0.answer_text}} <i class="glyphicon glyphicon-ok-sign pull-right"></i></p>
						{% else %}
						{% for answer in question.answers %}
							{% if answer.correct == True %}
								<p class="answer bg-success">{{answer.answer_text}} <i class="glyphicon glyphicon-ok-sign pull-right"></i></p>
							{% else %}
								<p class="answer">{{answer.answer_text}}</p>
							{% endif %}
						{% endfor %}
					{% endif %}
				</blockquote>
			{% endfor %}
		</div>
		
{% endif %}
<script type="text/javascript">
$('#process_csv').ajaxForm(function(data){
	beforeSend:$('.container').html('processing');
	success:$('.container').html(data);
});
</script>

sqs/templates/index.html
{% load static %}
<html>
<script src = "{%static "jquery/jquery.js" %}"></script>
<script src = "{%static "js/bootstrap.min.js" %}"></script>
<link href="{%static "jquery-ui.css" %}" rel="stylesheet">
<link href="{%static "css/bootstrap.min.css" %}" rel="stylesheet">
<script src = "{%static "jquery-ui.js" %}"></script>
<style>
	body{
		font-family: "Trebuchet MS", sans-serif;
		margin: 50px 100px 100px 100px;
		min-width: 800px;
	}
	.options{
		text-align:right;
		cursor: pointer;
		display: inline-block;
	}
	.container{
		margin-top: 3%;
		padding-left:5%;
		border-bottom: 1px dotted grey;
	}
	.leaderboard{		
		border-radius: 5px;
		max-height: 500px;
		overflow: auto;
	}

	.header h1{
		color:#2A2AD8;
	}
	a{
		color:#000;
	}
	</style>
{% if login_id %}
		<title>Leaderboards</title>
	{% else %}
		<title>Quiz App</title>
{% endif %}
<div class="header">
<h1>Student's Quiz System</h1>
<div class="ui-widget" style="border-bottom: 1px dotted grey;">
	<div style="float:left;font-weight:bold">Quizes will be conducted here and you can check leaderboards</div>
		<div class="pull-right">
	{% if login_id == None %}
		<a class="btn options btn-info" href='/'>Home</a>
		<div class="btn btn-success options" id="login">Login Here</div>
		<div class="btn btn-warning options" id="register">Register</div>
		{% else %}
		<a href="{{logged_user}}" class="btn btn-success">Home</a>
		<div class="btn btn-warning" id="logout">Logout</div>
	{% endif %}
		</div>
	<br></br>
</div>
</div>
<div class="container">
	
	<div class="row">
		<div class="col-md-6 leaderboard">
			<h4> City Leaderboard </h4>
			<table class="table table-striped table-bordered">
				<thead>
				<tr>
					<th>Student</th>
					<th>School</th>
					<th>City</th>
					<th>Quiz</th>
					<th>Score</th>
				</tr>
				</thead>
				{% for row in leaders %}
				<tr>
					<td>{{row.student_name}}</td>
					<td>{{row.school_name}}</td>
					<td>{{row.city_name}}</td>
					<td>{{row.quiz_name}}</td>
					<td>{{row.score}}</td>
				</tr>
				{% endfor %}
			</table>
		</div>
		<div class="col-md-6 leaderboard">
			<h4> School Leaderboard</h4>
			{% for school in school_leaders %}
			<table class="table table-striped table-bordered bg-warning">
				<thead>
				<tr>
					<th>Student</th>
					<th>School</th>
					<th>Quiz</th>
					<th>Score</th>
				</tr>
				</thead>
				{% for row in school %}
				<tr>
					<td>{{row.student_name}}</td>
					<td>{{row.school_name}}</td>
					<td>{{row.quiz_name}}</td>
					<td>{{row.score}}</td>
				</tr>
				{% endfor %}
			</table>
			{% endfor %}
		</div>
	</div>
	
</div>

<script>


$('#register').on('click',function(){
	$.ajax({
	  	url: "register",
	  	method:'GET',
	  	success:function(data){
	  		$('.container').html(data);
	  	},
	  	complete:$('.container').html('loading...')
	});
});


$('#login').on('click',function(){

	$.ajax({
	  	url: "login",
	  	method:'GET',
	  	success:function(data){
	  		$('.container').html(data);
	  	},
	  	complete:$('.container').html('loading...')
	});
});
$('#logout').on('click',function(){
	$.ajax({
  			url: "logout",
  			method:'GET',
  			success:function(data){$('body').html(data);window.location='/';},
  			complete:$('.container').html('Loggin Out...'),
  	});
});
function show_loading(){
	$('.container').html('Logging out...')
}
</script>
</html>

sqs/templates/login.html
{% if request.session.login_id == None %}

	{% if messages %}
		{% for message in messages %}
			<div class="alert alert-danger">{{message}}</div>
		{% endfor %}
	{% endif %}

	<form action="login" method = "post" id="login_form" style="width:50%;margin-left:auto;margin-right:auto">{% csrf_token %}
		<table class="table table-bordered">
			<tr>
				<td>Login as</td>
				<td>
					<select name="user">
						<option>student</option>
						<option>teacher</option>
					</select>
				</td>
			</tr>
			<tr>
				<td>Login ID</td>
				<td><input type="text" name="loginid" required></td>
			</tr>
			<tr>
				<td>Password</td>
				<td><input type="password" name="password" required></td>
			</tr>
			
			<tr><td></td><td><button type="submit" class="btn btn-primary">Login</button></td></tr>
		</table>
	</form>
	{% else %}
		Logged in as {{request.session.login_id}}
		<script type="text/javascript">
			window.location = '/{{request.session.logged_user}}'
		</script>
{% endif %}
<script type="text/javascript">

$('#login_form').submit(function( event ) {
  event.preventDefault();
  $.ajax({
  	url: "login",
  	method:'POST',
  	data:$(this).serialize(),
  	error:$('.container').html('Internal Error, Try Again'),
  	success:function(data){
  		$('.container').html(data);
  	},
  	complete:$('.container').html('loading...')
});
});

</script>

sqs/templates/quiz_details.html
<style type="text/css">
	blockquote{
		border-color:#AA6708;
		
	}
	.answer{
		padding:15px;
		width: 70%;
	}
</style>
<div class="row" id="quiz_container">
	<div>
		<h2>{{quiz_data.title}} <span class="pull-right">Score:{{score}}</span></h2> 
	</div>

	<div>
		{% for question in quiz_data.questions %}
		<blockquote>
			<p>{{question.question_text}} </p>
				{% if question.choice == 1 %}
					{% if question.option == question.answers.0.answer_text %}
						<p class="answer bg-success">{{question.answers.0.answer_text}} <i class="glyphicon glyphicon-ok-sign pull-right"></i></p>
					{% else %}
						<p class="answer bg-danger">{{question.option}} <i class="glyphicon glyphicon-remove-sign pull-right"></i></p>
						<p class="answer bg-success">{{question.answers.0.answer_text}} <i class="glyphicon glyphicon-ok-sign pull-right"></i></p>
					{% endif %}
				{% else %}
				{% for answer in question.answers %}
					{% if question.option == answer.id and answer.correct == False %}
						<p class="answer bg-danger"  id="radio_{{answer.question}}"  data="{{answer.id}}"><input type="radio" checked disabled> {{answer.answer_text}}<i class="glyphicon glyphicon-remove-sign pull-right"></i>
					{% elif question.option == answer.id and answer.correct == True %}
						<p class="answer bg-success"  id="radio_{{answer.question}}"  data="{{answer.id}}"><input type="radio" checked disabled> {{answer.answer_text}}<i class="glyphicon glyphicon-ok-sign pull-right"></i>
					{% elif answer.correct == True %}
						<p class="answer bg-success"  id="radio_{{answer.question}}"  data="{{answer.id}}"><input type="radio" disabled> {{answer.answer_text}}<i class="glyphicon glyphicon-ok-sign pull-right"></i>
					{% else %}
						<p class="answer "  id="radio_{{answer.question}}"  data="{{answer.id}}"><input type="radio" disabled> {{answer.answer_text}}
					{% endif %}
					</p>
					
				{% endfor %}
			{% endif %}
		</blockquote>
		{% endfor %}

		

	</div>

</div>
<script type="text/javascript">
	var student_answers = "{{student_answers}}";
	console.log(student_answers);
</script>

sqs/templates/quiz_setup.html
{% if quiz_id %}
  <script type="text/javascript">
    $.ajax({
    url: "csv_upload",
    method:'GET',
    data:$(this).serialize(),
    error:$('#quiz_setup').html('Internal Error, Try Again'),
    success:function(data){
      $('#quiz_setup').html(data);
      $('#process_csv').append('<input type="text" value="{{quiz_id}}" name="quiz_id">');
    },
    complete:$('#quiz_setup').html('loading...')
   });

  </script>

  {% else %}
<h4>New Quiz Setup</h4>
  <form method="post" action="quiz_setup" id="quiz_setup_form">{% csrf_token %}
  <input type="hidden" value="{{display}}" name="display">
  <table class="table table-bordered">
  {{ quizf.as_table }}
  {{ quesf.as_table }}
  {{ answf.as_table }}

  <tr><td></td><td><button type="submit" class="btn btn-primary">Save</button></td></tr>
  </table>
  </form>
  

{% endif %}
<script type="text/javascript">
	$('#id_quiz-start_date').datepicker({ minDate: 0 });
	$('#id_quiz-end_date').datepicker({ minDate: 0 });
	$('#id_start_date').datepicker({ minDate: 0 });
	$('#id_end_date').datepicker({ minDate: 0 });

$('#quiz_setup_form').submit(function( event ) {
  event.preventDefault();

  $.ajax({
  	url: "quiz_setup",
  	method:'POST',
  	data:$(this).serialize(),
  	error:$('#quiz_setup').html('Internal Error, Try Again'),
  	success:function(data){
  		$('#quiz_setup').html(data);
  	},
  	complete:$('#quiz_setup').html('loading...')
   });

});

</script>